name: Advanced Azure Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 수동 실행 가능

env:
  PYTHON_VERSION: '3.11'
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_APP_NAME }}
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install azure-functions azure-identity
        
    - name: Run tests
      run: |
        echo "Running application tests..."
        python -c "
        import sys
        sys.path.append('.')
        from src.integrated_risk_analyzer import IntegratedRiskAnalyzer
        from src.config import Config
        print('✅ All imports successful')
        "
        
    - name: Create deployment package
      run: |
        echo "Creating deployment package..."
        # 필요한 파일들만 패키징
        mkdir -p deploy_package
        cp -r src deploy_package/
        cp app_streamlit.py deploy_package/
        cp requirements.txt deploy_package/
        cp -r pdfs deploy_package/
        cp sample_*.json deploy_package/
        cp README.md deploy_package/
        
        # Azure App Service용 startup 명령어 생성
        echo "streamlit run app_streamlit.py --server.port=8000 --server.address=0.0.0.0" > deploy_package/startup.sh
        chmod +x deploy_package/startup.sh
        
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: deploy_package
        
    - name: Verify deployment
      run: |
        echo "Deployment completed successfully!"
        echo "Application should be available at: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
